#!/usr/bin/env python3
"""
Generate vocabulary report
"""
import argparse
import json
import sys
from pathlib import Path
from datetime import datetime


def generate_report(vocab_path: Path, output_path: Path):
    """Generate markdown report"""
    
    # Load vocabulary
    with open(vocab_path, 'r', encoding='utf-8') as f:
        vocab_data = json.load(f)
    
    metadata = vocab_data.get('metadata', {})
    vocab = vocab_data.get('vocab', {})
    
    # Load stats if available
    stats_path = vocab_path.parent / vocab_path.name.replace('vocab_', 'vocab_stats_')
    stats = {}
    if stats_path.exists():
        with open(stats_path, 'r') as f:
            stats = json.load(f)
    
    # Generate report
    report = f"""# Vocabulary Training Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Vocabulary Information

- **Size:** {metadata.get('vocab_size', len(vocab)):,} tokens
- **Algorithm:** {metadata.get('algorithm', 'Unknown')}
- **Created:** {metadata.get('created_at', 'Unknown')}
- **File:** `{vocab_path.name}`

## Special Tokens

{chr(10).join(f'- `{token}`' for token in metadata.get('special_tokens', []))}

## Statistics

"""
    
    if stats:
        report += f"""- **Sample Files:** {stats.get('sample_files', 'N/A')}
- **Total Tokens (sampled):** {stats.get('total_tokens_sampled', 0):,}
- **Total Characters (sampled):** {stats.get('total_chars_sampled', 0):,}
- **Avg Characters per Token:** {stats.get('avg_chars_per_token', 'N/A')}
- **Compression Ratio:** {stats.get('compression_ratio', 'N/A')}x

"""
    
    report += f"""## Vocabulary Size Comparison

| Model | Vocabulary Size |
|-------|----------------|
| **KuiperAI (This)** | **{metadata.get('vocab_size', len(vocab)):,}** |
| GPT-2 | 50,257 |
| GPT-3 | 50,257 |
| BERT | 30,522 |
| LLaMA | 32,000 |
| GPT-4 | ~100,000 |

## Usage

### Loading the Tokenizer

```python
from tokenizers import Tokenizer

# Load tokenizer
tokenizer = Tokenizer.from_file("checkpoints/{vocab_path.name.replace('vocab_', 'tokenizer_')}")

# Encode text
text = "Hello, world!"
encoding = tokenizer.encode(text)
print(encoding.tokens)

# Decode tokens
decoded = tokenizer.decode(encoding.ids)
print(decoded)
```

### Integration with Model

```python
import json
from tokenizers import Tokenizer

# Load vocabulary
with open("{vocab_path.name}", 'r') as f:
    vocab_data = json.load(f)
    vocab = vocab_data['vocab']

# Load tokenizer
tokenizer = Tokenizer.from_file("{vocab_path.name.replace('vocab_', 'tokenizer_')}")

# Update model
model = Transformer(
    vocab_size=len(vocab),
    d_model=512,
    num_heads=8,
    num_layers=6
)
```

## Next Steps

1. ✅ Vocabulary trained successfully
2. 🔄 Retrain model with new vocabulary
3. 🔄 Test generation quality
4. 🔄 Fine-tune on specific tasks

---

*This report was automatically generated by the vocabulary training pipeline.*
"""
    
    # Write report
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(report)
    
    print(f"✅ Report generated: {output_path}")


def main():
    parser = argparse.ArgumentParser(description='Generate vocabulary report')
    parser.add_argument('--vocab-path', type=str, required=True,
                       help='Path to vocabulary JSON')
    parser.add_argument('--output', type=str, required=True,
                       help='Output markdown file')
    
    args = parser.parse_args()
    
    vocab_path = Path(args.vocab_path)
    output_path = Path(args.output)
    
    if not vocab_path.exists():
        print(f"❌ Error: Vocabulary not found: {vocab_path}")
        sys.exit(1)
    
    generate_report(vocab_path, output_path)


if __name__ == "__main__":
    main()
